steps:
- name: 'docker'
  id: create-image
  args:
  - build
  - -t
  - us-docker.pkg.dev/${PROJECT_ID}/pokemon/pokemon-yes
  - .

- name: 'docker'
  id: push-image
  args:
  - push
  - us-docker.pkg.dev/${PROJECT_ID}/pokemon/pokemon-yes